version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  toposoid-component-dispatcher-web:
    image: toposoid/toposoid-component-dispatcher-web:0.1.0
    tty: true
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - PRIVATE_IP_ADDRESS=localhost
      - PLAY_HTTP_PORT=9004
      - SENTENCE_PARSER_WEB_HOST=172.30.0.7
      - DEDUCTION_ADMIN_WEB_HOST=172.30.0.6
    networks:
      app_net:
        ipv4_address: 172.30.0.8
    ports:
      - 9004:9004
    depends_on:
      - toposoid-deduction-admin-web
      - toposoid-sentence-parser-web
  toposoid-sentence-parser-web:
    image: toposoid/toposoid-sentence-parser-web:0.1.0
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.7
      - PLAY_HTTP_PORT=9001
    networks:
      app_net:
        ipv4_address: 172.30.0.7
    ports:
      - 9001:9001
  toposoid-deduction-admin-web:
    image: toposoid/toposoid-deduction-admin-web:0.1.0
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=172.30.0.6
      - PLAY_HTTP_PORT=9003
      - DEDUCTION_UNIT1_HOST=172.30.0.5
      - DEDUCTION_UNIT2_HOST=172.30.0.4
    networks:
      app_net:
        ipv4_address: 172.30.0.6
    ports:
      - 9003:9003
    depends_on:
      - toposoid-deduction-unit-exact-match-web
      - toposoid-deduction-unit-synonym-match-web
  toposoid-deduction-unit-exact-match-web:
    image: toposoid/toposoid-deduction-unit-exact-match-web:0.1.0
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=localhost
      - SCALA_DATA_ACCESSOR_NEO4J_WEB_HOST=172.30.0.3
      - PLAY_HTTP_PORT=9005
    networks:
      app_net:
        ipv4_address: 172.30.0.5
    ports:
      - 9005:9005
    depends_on:
      - scala-data-accessor-neo4j-web
  toposoid-deduction-unit-synonym-match-web:
    image: toposoid/toposoid-deduction-unit-synonym-match-web:0.1.0
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=localhost
      - SCALA_DATA_ACCESSOR_NEO4J_WEB_HOST=172.30.0.3
      - PLAY_HTTP_PORT=9102
    networks:
      app_net:
        ipv4_address: 172.30.0.4
    ports:
      - 9102:9102
    depends_on:
      - scala-data-accessor-neo4j-web
  scala-data-accessor-neo4j-web:
    image: toposoid/scala-data-accessor-neo4j-web:0.1.0
    tty: true
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - PRIVATE_IP_ADDRESS=localhost
      - PLAY_HTTP_PORT=9005
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    ports:
      - 9005:9005
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:4.1.3
    environment:
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_AUTH=neo4j/p@ssw0rd
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      app_net:
        ipv4_address: 172.30.0.2

